# Generated by Django 4.1.5 on 2023-01-12 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('nickname', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('rounds_played', models.PositiveIntegerField(default=0)),
                ('rounds_won', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('profile', 'Offensive nickname or profile photo'), ('inactivity', 'Inactivity during the game'), ('ruining', 'Intentional ruining the game'), ('cheating', 'Cheating')], default=('profile', 'Offensive nickname or profile photo'), max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('report_datetime', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL, verbose_name='who has been reported')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_author', to=settings.AUTH_USER_MODEL, verbose_name='who has reported')),
            ],
        ),
    ]
