# Generated by Django 4.1.5 on 2023-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['order'], 'verbose_name': 'post'},
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
