# Generated by Django 4.1.5 on 2023-01-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_options_remove_profile_id_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
    ]
