# Generated by Django 4.1.5 on 2023-01-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cards',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='card_on_table',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='cards_remain',
            field=models.CharField(default='1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100', max_length=300),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='levels',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='lives',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='players_number',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='throwing_stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
